# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Unsplasher' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Unsplasher
  pod 'SnapKit'
  pod 'Then'
  pod 'RealmSwift'

end
